name: petastorm_debug
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.7
  - pip
  - python-dotenv>=0.5.1
  - pyarrow=3.0.0
  - numpy=1.20
  - distributed=2021.02.0
  - fastparquet
  - pytorch=1.7.0 
  - torchvision=0.8
  - torchaudio=0.7 
  - cudatoolkit=10.2
  - pytorch-lightning=1.4.9
  - torchmetrics>=0.5
  - tensorboardx
  - pyspark=3.1.2
  - pip:
    - petastorm==0.11.3

variables:
  USE_TORCH: 1